== Create OAuth Integrated and Pre-Step Consent

[role="arc42help"]
****
.Contents
A short step by step instruction how to create an OAuth integrated and pre-step consent approach in our Dynamic Sandbox with Postman.
****

NOTE: Please, note, that all steps are for the developer environment and not the DEMO.

=== OAuth Integrated Consent

_If you have registered a TPP and created a PSU user, you can skip steps 1-3._

[start=1]
. Click on: https://dev-dynamicsandbox-tppui.cloud.adorsys.de/login and register a new TPP account.
. Login with the new registered TPP, click on _My user list_ and create a new user. In our example it is _aguex8_, with the pin _aguex8_ and the static TAN _123456_.
. Create for this user at least one account with a generated IBAN.
. Now open Postman and import the collection “postman_collection_oauth_pre-step_integrated.json” and the environment “Xs2a DEV ENV.postman_environment.json” from our postman-scripts. Then, switch environment to `Xs2a DEV ENV`.
. Open the POST request “intitiate consent” of the imported collection.
. Change in the header the `psu-id` to user login, in our example it is _aguex8_, and set `X-OAUTH-PREFERRED` to “integrated”.
. Press Send and you will receive the `consentId` and multiple links (scaOAuth, self, status, scaStatus).
. Press on the first link scaOAuth to open new Postman tab, press Send again.
. Now you will receive two links, the `authorization_endpoint` and the `token_endpoint`, copy the first link and open it in a web browser.
. Login with your `psd-ui`, press Next, select a sca method, enter the static TAN and press Next again. Finally, click on “Go Back to TPP page”.
. “Go Back to TPP page” leads you to a Google link with your code. Grab the code from the end of the redirected url. In our example the url is https://www.google.com/?code=n4Pwq3neZx5FkSF8EzioCL75 and the resulting code `n4Pwq3neZx5FkSF8EzioCL75`.
. Go back to Postman and open the second link as new Postman tab by clicking on it. Add to header the attribute “code” with code of the previous step as value and press Send.
. Finally, you receive your access token, which enables you in Postman to do AIS requests like GET “Read Account List” in OAuth2.0 flow. Select as Authorization “Bearer token” and paste the access token there and use as consentId the one you received in step 7.

